- hosts: servers
  roles:
     - role: chrony
       chrony_allow_enable: true
       chrony_allow:
         - 10.10.10.0/24
         - 127.0.0.1
         - ::/0
       chrony_disable_ntpd: true
       chrony_enable: true
       chrony_log_enable: true
       chrony_log: measurements statistics tracking
       chrony_logdir: /var/log/chrony/
       chrony_ntp_servers:
         - time1.google.com 
         - time2.google.com 
         - time3.google.com
         - time4.google.com         
       chrony_rtcsync: true
       chrony_smearing: true
       chrony_timezone: "Asia/Dhaka"
