---
- name: Configure UFW firewall
  hosts: all
  become: yes
  tasks:
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow SSH from specific IPs
      ufw:
        rule: allow
        port: 22
        proto: tcp
        src: "{{ item }}"
      loop:
        - 182.163.127.236
        - 202.84.42.5

    - name: Allow HTTP Access
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS Access
      ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
