---
- name: Regularly upgrade Ubuntu packages
  hosts: your_server_group
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
