---
- hosts: all
  become: yes
  vars_files:
    - vars/default.yaml
  tasks:
    - name: "Install prerequisites"
      apt: 
        name: '{{ item }}'
        update_cache: yes 
        state: latest 
        force_apt_get: yes
      loop: 
        - aptitude

  #Apache Configuration
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
    - name: Install LAMP Packages
      apt: 
        name: "{{ item }}" 
        update_cache: yes 
        state: latest
      loop:
        - apache2 
        - mysql-server 
        - python3-pymysql 
        - php
        - pip
        - ufw
        - php-mysql 
        - libapache2-mod-php
        - python3-pip
        - python3-mysqldb
        - php-gd
        - php-cli
        

    - name: Install pyMySQL
      pip:
        name: pymysql
        state: present
      ignore_errors: True

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
      
    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  # MySQL Configuration
  # - name: Sets the root password
  #    mysql_user:
  #    name: root
  #    password: "{{ mysql_root_password }}"
  #    login_unix_socket: /var/run/mysqld/mysqld.sock
  #    ignore_errors: True
    
    - name: Set root user password
      mysql_user:
         name: root
         password: "{{ mysql_root_password }}"
         check_implicit_admin: yes
         login_user: root
         login_password: "{{ mysql_root_password }}"
         state: present
    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Removes the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ http_host }}/index.php"

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
