---
- name: "Testing by gathering Facts"
  hosts: switches
  gather_facts: yes

- tasks:
  - name: Gather only the config and default facts
    cisco.ios.ios_facts:
      gather_subset:
      - config
